### ISSUE TITLE
Refreshing while scrolling causes images to shift

### ISSUE THREAD

**Issue by jerriclynsjohn** [cyntss/Parallax-img-scroll#1]
Trying to refresh while in between of the page makes the elements to disappear and while scrolling up after that makes the images to be displaced clearly making it loose the parralax effect.

**Comment by cyntss** [comment]
Thank you for reporting, I will work on this issue ASAP :+1:

**Comment by cyntss** [comment]
Issue resolved.
https://github.com/cyntss/Parallax-img-scroll/blob/master/parallaxImg.js
